# -*- coding: utf-8 -*-
"""Figure2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Takwim6IDOUFHBlr_4o_8hkKJkmA8kPQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read in the line in the file that is pertinent
pilra_speeds = pd.read_csv('pilra_speeds.txt', skiprows=[0,2,3,4,5,6,7],
                           dtype=np.float64, header=None)

pilra_mutant_speed = pd.read_csv('pilra_mutant_speeds.txt', skiprows=[0],
                                dtype=np.float64, header=None)

# Calculate sliding window means 

speeds = pilra_speeds.values[0]
N = 9 # Use a 9-codon window (the default setting for ExtRamp)
windowMeans = pd.Series(speeds).rolling(window=N).mean().iloc[N-1:].values

mutant_speeds = pilra_mutant_speed.values[0]
N = 9
mutant_windowMeans = pd.Series(mutant_speeds).rolling(window=N).mean().iloc[N-1:].values

positions = range(1, 295) # for x-axis

# Plot the data

plt.plot(positions, mutant_windowMeans, 'r', label="rs2405442")
plt.plot(positions, windowMeans, 'b', label="Consensus Sequence")
#plt.plot()
plt.xlim([0,301]) # Doesn't run when set to 300...?
plt.ylim([0,1.1])
plt.ylabel('Relative Codon Adaptiveness') 
plt.xlabel('Codon Position')
plt.title('Predicted Codon Adaptiveness for PILRA') 
plt.annotate('Ramp sequence region', xy=(25,.6),
             xytext=(25, .3), arrowprops=dict(facecolor='black', shrink=0.05))
plt.legend(loc="lower right")
plt.show()

